# For more information about the available options please visit: http://go/backstage (VPN required)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: Unity-Technologies/immersive-commerce-sample
  name: immersive-commerce-sample
  description: "Sample game showcasing Immersive Commerce"
  labels:
    costcenter: "1087"
  tags:
    - planned-public
    - enterprise
  links:
    - url: https://unity.slack.com/messages/C06051R4CGP/
      title: "#ask-orca-commerce-service"
      icon: chat
spec:
  type: other
  lifecycle: experimental
  owner: unity-technologies/ind-proj-orca-admins
